server:
  port: 8763
spring:
  application:
    name: feign
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 1000
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 200000
        readTimeout: 200000